[project]
name = "crawl-github-starred"
version = "0.1.0"
description = "Crawl GitHub for starred items"
requires-python =">=3.11"
dependencies = [
    "requests==2.31.0",
    "backoff==2.2.1"
]

[build-system]
requires = ["uv"]
build-backend = "uv"