[project]
name = "crawl-github-starred"
version = "0.1.0"
description = "Crawl GitHub for starred items"
requires-python =">=3.11"
dependencies = [
    "requests==2.31.0",
    "stamina==24.3.0"
]

[build-system]
requires = ["uv==0.6.4"]
build-backend = "uv"